---
- name: Copy ssh keys and config
  copy: src={{ item }} dest=/root/.ssh/{{ item }} owner=root mode=0600
  with_items:
    - github_key
    - github_key.pub
    - config

- name: Download omd sources
  get_url: url=http://files.omdistro.org/releases/debian_ubuntu/omd-1.00_0.{{ ansible_distribution_release }}_amd64.deb dest=/tmp/omd-1.00_0.deb
  when: ansible_userspace_architecture == "x86_64"

- name: Download omd sources
  get_url: url=http://files.omdistro.org/releases/debian_ubuntu/omd-1.00_0.{{ ansible_distribution_release }}_i386.deb dest=/tmp/omd-1.00_0.deb
  when: ansible_userspace_architecture == "i386"

- name: Install omd package
  command: dpkg -i /tmp/omd-1.00_0.deb

- name: Enable apache module
  command: a2enmod proxy_http
  notify: restart apache

- name: Create workspace directory
  file: path=/omd/workspace state=directory

- name: Clone repo 
  git: repo=ssh://git@github.com/sseshachala/MonitoringAPI.git dest=/omd/workspace/MonitoringAPI

# - name: Change cloned repo permissions
#   file: path=/omd/workspace/MonitoringAPI group={{omd_group}} owner=root  recurse=yes state=directory

- name: Make OMD Symbolic links
  file: src=/omd/workspace/MonitoringAPI/xervrest/{{item}} dest=/omd/versions/default/{{item}} state=link
  with_items:
    - share/xervrest
    - skel/etc/xervrest
    - skel/etc/apache/conf.d/0xervrest.conf
    - bin/install_omd_agent.py

- name: Create log omd directory
  file: path=/omd/versions/default/skel/var/log/omd-agent-installer state=directory

- name: Create log file
  # not working in 1.3. Currently in devel
  # file: path=/omd/versions/default/skel/var/log/omd-agent-installer/omd-agent-installer.log state=touch
  copy: src=empty dest=/omd/versions/default/skel/var/log/omd-agent-installer/omd-agent-installer.log

- name: Clone Collectd config
  git: repo=ssh://git@github.com/sseshachala/collectd_config.git dest=/omd/workspace/collectd_config

- name: Install graphite
  shell: /omd/workspace/collectd_config/installer/install.sh graphite || /bin/true chdir=/omd/workspace/collectd_config/installer executable=/bin/bash

# - name: Create symlinks for graphite
#   file: src=/omd/workspace/MonitoringAPI/graphios/{{item}} dest=/omd/versions/default/{{item}} state=link
#   with_items:
#     - bin/graphios_site_migrate.py
#     - bin/graphios.py
#     - skel/etc/graphios
#     - skel/etc/init.d/graphios

# - name: More symlink
#   file: src=/omd/versions/default/skel/etc/init.d/graphios dest=/omd/versions/default/skel/etc/rc.d/98-graphios state=link

- name: Remove files
  file: path=/omd/versions/default/{{ item }} state=absent
  with_items:
    - share/omd/skel.permissions
    - skel/etc/pnp4nagios/process_perfdata.cfg
    - lib/pnp4nagios/process_perfdata.pl

- name: More symlinkng
  file: src=/omd/workspace/MonitoringAPI/graphios/{{ item }} dest=/omd/versions/default/{{item}} state=link
  with_items:
    - share/omd/skel.permissions
    - skel/etc/pnp4nagios/process_perfdata.cfg
    - lib/pnp4nagios/process_perfdata.pl

- name: Change Permission graphios
  file: path=/omd/workspace/MonitoringAPI/graphios/skel/etc/init.d/graphios mode=755
