---
- name: Install mysql package
  apt: pkg={{ item }}
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start mysql Service
  service: name=mysql state=started enabled=true

- name: Update mysql root password
  mysql_user: name=root password={{dbpassword}} state=present check_implicit_admin=yes login_user=root login_password={{dbpassword}}
