---
- name: Create workspace directory
  file: path=/omd/workspace state=directory

- name: Clone Collectd config
  git: repo=ssh://git@github.com/sseshachala/collectd_config.git dest=/omd/workspace/collectd_config

- name: Install graphite
  shell: /omd/workspace/collectd_config/installer/install.sh graphite || /bin/true chdir=/omd/workspace/collectd_config/installer executable=/bin/bash

- name: Copy carbon conf file
  template: src={{ item }}.example dest=/opt/graphite/conf/{{ item }}
  with_items:
    - carbon.conf
  notify:
    - restart carbon-cache
    - restart apache


