- name: Remove instance
  local_action: ec2 aws_access_key={{aws_access_key}} aws_secret_key={{aws_secret_key}} keypair={{keypair}} state=absent instance_id={{item}} region={{region}}
  with_items: ec2.instance_ids
    

