- name: Create vol
  hosts: local
  connection: local
  gather_facts: false

  vars_files:
    - "vars/amazon_creds.yml"

  roles:
    - create_vol

- name: Delete vol
  hosts: local
  connection: local
  gather_facts: false

  pre_tasks:
    - debug: msg="Volume {{volume}} ."

  vars_files:
    - "vars/amazon_creds.yml"

  roles:
    - delete_vol

