---
- name: Install apache, mysql, php, xmd, graphios
  hosts: xmd
  user: root
  roles:
    - common
    - web
    - db
    - xmd
    - graphios

- name: Install graphite
  hosts: graphite
  user: root
  roles:
    - common
    - graphite

