#! /bin/bash
#
# simple init script for xervpyapi
#
#
# chkconfig: 345 99 01
# description: xervpyapi -> xervpyapi script
#
# File : xervpyapi

prog="###ROOT###/bin/xervpyapi"
RETVAL=0

start () {
        echo -n "Starting xervpyapi..."
        $prog &
        RETVAL=$?
        if [ $RETVAL -eq 0 ] 
        then
            echo "OK"
        else
            echo "FAILED"
        fi
}

stop () {
        echo -n "Stopping xervpyapi..."
        if [ -e ###ROOT###/tmp/xervpyapi.pid ]
        then
            kill `cat ###ROOT###/tmp/xervpyapi.pid`
            RETVAL=$?
            if [ $RETVAL -eq 0 ]
            then
                if [ -e ###ROOT###/tmp/xervpyapi.pid ]
                then
                    rm ###ROOT###/tmp/xervpyapi.pid
                fi
                echo "OK"
            else
                echo "FAILED"
            fi
        else
            echo "WARNING (NO PID FILE FOUND)"
        fi
}

restart () {
        stop
        start
}


# See how we are called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo "Usage: service xervpyapi {start|stop|restart|reload}"
        RETVAL=2
        ;;
esac

exit $RETVAL

