- name: Spin instance
  local_action: ec2 aws_access_key={{aws_access_key}} aws_secret_key={{aws_secret_key}} keypair={{keypair}} group={{security_group}} instance_type={{instance_type}} image={{image}} wait=true region={{region}}
  register: ec2
